apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-1
  labels:
    name: simple-webapp
spec:
  containers:
    - name: c1
      image: kodekloud/webapp-delayed-start
      imagePullPolicy: Always
      env:
      - name: APP_START_DELAY
        value: "80"
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
        initialDelaySeconds: 80
        periodSeconds: 1