apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    name: webapp-color
  namespace: default
spec:
  containers:
    - name: webapp-color
      image: kodekloud/webapp-color
      imagePullPolicy: Always
      env:
      - name: APP_COLOR
          value: green