apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
  labels:
    name: appointment-management
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: spring-boot-appointment
      labels:
        app: spring-boot-appointment
    spec:
      containers:
      - name: spring-boot-appointment
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: config-map-portail
                key: postgres_host
        image: abdelkarim123/spring-appointment-management:2.0.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: svc-appointment
spec:
  type: LoadBalancer
  ports:
    - port: 8083
  selector:
    app: appointment-management