apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-management
  labels:
    app: citizen-management
  namespace: default
spec:
  selector:
    matchLabels:
      app: citizen-management
  replicas: 1
  template:
    metadata:
      name: citizenPod1
      labels:
        app: citizen-management
    spec:
      containers:
      - name: citizen-container-1
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: config-map-portail
                key: postgres_host
        image: abdelkarim123/spring-citizen-management:2.0.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: svc-citizen
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: citizen-management
