apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-management
  labels:
    name: request-management
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: request-management
      labels:
        app: request-management
    spec:
      containers:
      - name: request-management
        image: abdelkarim123/spring-request-management:2.0.6
        imagePullPolicy: IfNotPresent
        env:
          - name: CM_HOST
            valueFrom:
              configMapKeyRef:
                name: config-map-portail
                key: cm_host
---
apiVersion: v1
kind: Service
metadata:
  name: svc-request
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: request-management