apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pod1
  template:
    metadata:
      labels:
        name: pod1
    spec:
      containers:
      - name: c1
        image: httpd:2.4-alpine
